# GitArena config file

bind = "localhost:8080"
domain = "https://gitarena.com"
database = "postgresql://root@localhost/gitarena?sslmode=require"
secret = "" # Needs to be at least 32 bytes long

[repositories]
base_dir = "repositories"

[hcaptcha]
enabled = false
site_key = ""
secret = ""

[smtp]
server = "smtp.gitarena.com"
port = 465
tls = true
email_address = "noreply@gitarena.com"
username = "root"
password = "hunter2"
